### PR TITLE
move things into subfolders to clean up the project root a bit

### PR DESCRIPTION
**Pull request by rhroberts**
Would like everyone's OK on this one. Wanted to tidy up a bit post-jam. Suggestions and changes welcome.  

I think my enter patients scene is borked from Monday, but that will get fixed with #29

### CODE REVIEW

**Review by halfhorst — APPROVED** [review]

**Comment by halfhorst** [comment]
lgtm

**Review by dmarc3 — APPROVED** [review]
Full send it!

**Review by CurtisRT — COMMENTED** [review]
I approve!

**Comment by rhroberts** [comment]
wow you all are so prompt! ty

**Pull request merged**
